### ISSUE TITLE
bowtie2-build version incompatible

### ISSUE THREAD

**Issue by Arkarachai** [Novartis/EQP-cluster#1]
Hi,

I tried to install EQP-cluster and I run into the dependency issue. I have bowtie2 2.2.3 and your program require >=2.0.5; however, the installation still exit. Do you have any recommendation?

Thank you,
Chai

sh create-bowtie2-indices.sh 
Extracting directory exon-pipeline-files
create-bowtie2-indices.sh: 287: create-bowtie2-indices.sh: source: not found
Please use bowtie2-build version >= 2.0.5. Found version: 2.2.3 ... exiting

**Comment by sven0schuierer** [comment]
Hi Chai,

Sorry, about that. There was a bug in the script. Please try again with the attached version.

Best regards,

Sven

**Comment by Arkarachai** [comment]
Hi Sven,
 Thank you for your prompt reply. I cannot see the attached version. However, I try with bowtie 2.0.5 and it seems to work fine. 

Thank you,
Chai
